### ISSUE TITLE
Could you provide the data download link 

### ISSUE THREAD

**Issue by xmengli** [Cory-M/DCCM#4]
Thanks for your code. 

I found it is difficult to get the same data as your meta file. Could you provide your cifar10 data download link?

Thank you

**Comment by Cory-M** [comment]
sorry for the late reply. It was normal data resource, and I generated the metafile from the data -- you can generate your own metafile from your data arrangement as well. I don't have a specific download link, since it was the organized data on our company's cluster, but it's just normal CIFAR10/100 data in some order, and yours would work fine too.

**Comment by Cory-M** [comment]
if it would be helpful -- the metafile was basically generated by os.listdir(data_folder). it's a trivial generation😂
